### ISSUE TITLE
Use `Bunny::Exchange#on_return` to improve visibility of unconsumed messages

### ISSUE THREAD

**Issue by xiazek** [RenoFi/jackhammer#28]
There is nice and easy option to gain additional logs/alerts in case messages are not delivered: 
 `Bunny::Exchange#on_return`.

It could be used to allow i.e. raising exception or adding proper log in case there is no consumer connected for an exchange a message was published to. 

Usage example & more info: 
http://rubybunny.info/articles/exchanges.html#publishing_messages_as_mandatory

**Comment by scottserok** [comment]
👍  a nice feature to allow clients to configure the `on_return` handler if they want to. That's currently not possible with the current Jackhammer implementation.  Maybe something similar to how the exception_adapter is configured today?
